# server config
server:
  port: 8002
  
# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##BOOKSHOP
    password: BOOKSHOP
# file upload config
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: iCloud Drive/데스크탑/bookshop/

# image upload directory
image: 
  image-dir: src/main/resources/upload/   
      
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
  

